server:
  port: 8765

eureka:
    instance:
        statusPageUrlPath: /actuator/info
        healthCheckUrlPath: /actuator/health
        home-page-url-path: /
        lease-expiration-duration-in-seconds: 30
        lease-renewal-interval-in-seconds: 10
        # docker 部署开启
        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
            defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true


ribbon:
  eureka:
    enabled: true
  ReadTimeout: 30000
  ConnectTimeout: 30000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 100 ##并发执行的最大线程数，默认10
      maxQueueSize: 500##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 50 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000


spring:
  application:
      name: Zuul
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true

logging:
  level:
    springcloud.gateway: info
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: info
    org.springframework.web.reactive: info
    reactor.ipc.netty: info

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
